WIP: modified queries by using flattening tables
ImagingDataCommons/etl_flow pull request #64
Opened 2023-02-20 15:03 UTC by vkt1414

2023-02-20 15:20 UTC, vkt1414 commented
this post shows why it may be better to use LEFT JOIN instead of CROSS JOIN while unnesting..https://www.yuichiotsuka.com/google-bigquery-unnest-arrays/
and this document also shows why CROSS JOINS can sometimes be tricky
[BigQuery_UNNEST_example_Towards_Data_Science.pdf](https://github.com/ImagingDataCommons/etl_flow/files/10785664/BigQuery_UNNEST_example_Towards_Data_Science.pdf)

2023-02-20 15:21 UTC, fedorov commented
@bcli4d for the context, this is the work to update our derived queries to handle the attributes specific to the new collection, and at the same time optimize/simplify the queries to make those additions easier. Vamsi and I are working to finalize this today.

2023-02-20 19:06 UTC, fedorov commented
Few other minor comments:
* make sure there not extra columns that are not used that are introduced in the output (need to confirm)
* add tab to the nested levels of the query

2023-02-20 19:07 UTC, fedorov requested changes

2023-02-20 19:08 UTC, fedorov commented
@deepakri201 can you please take the queries here and do your testing to confirm they work as expected for you? Looks great to me, but I would appreciate your checks as well.

2023-02-20 22:59 UTC, vkt1414 commented on bq/derived_table_creation/BQ_Table_Building/derived_data_views/sql/measurement_groups.sql
> +  (cs_l2.ValueType IN ('TEXT') AND cs_l2_cncs.CodeValue IN ('112039')AND cs_l2_cncs.CodingSchemeDesignator IN ('DCM'))
adjusted formatting and added codemeanings

2023-02-21 17:43 UTC, fedorov commented
@s-paquette the updated queries will result in some new values - it would be good if you checked them before we finalize this.

2023-02-21 18:14 UTC, fedorov commented on bq/derived_table_creation/BQ_Table_Building/derived_data_views/sql/measurement_groups.sql
> +    -- Tracking Identifier--TEXT value type with specific Code Value and Coding Scheme Designator
@vkt1414 what I suggested earlier is to include CodeMeaning value corresponding to the CodeValue/CodingSchemeDesignator values in the line below. So, in this particular example, CodeMeaning = "Tracking Identifier". Does it make sense? Can you add values of CodeMeaning corresponding to each combinations of CodeValue/CodingSchemeDesignator in this and other queries?

2023-02-21 18:36 UTC, fedorov commented on bq/derived_table_creation/BQ_Table_Building/derived_data_views/sql/measurement_groups.sql
> +    -- Tracking Identifier--TEXT value type with specific Code Value and Coding Scheme Designator
Sorry, I meant mention CodeMeaning in the line above, in the comment - not in the query itself - just to make the query more readable.

2023-02-21 19:01 UTC, fedorov commented on bq/derived_table_creation/BQ_Table_Building/derived_data_views/sql/measurement_groups.sql
> +    -- Tracking Identifier--TEXT value type with specific Code Value and Coding Scheme Designator
Never mind, I see I missed it. This is what happens with multitasking. It's all good!

2023-02-21 19:05 UTC, fedorov approved these changes

2023-02-21 19:13 UTC, merged